### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by edtan094**

### CODE REVIEW

**Comment by edtan094** [comment]
loading-spinner
mobile-responsiveness
mobile-responsiveness part 2

**Comment by edtan094** [comment]
mobile-responsiveness part 3

**Comment by edtan094** [comment]
pointers-and-hovers

**Comment by edtan094** [comment]
no-weapons-found

**Comment by edtan094** [comment]
no-weapons-saved

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
